### ISSUE TITLE
Choose a suitable license for the project.

### ISSUE THREAD

**Issue by PopeSpaceous** [PopeSpaceous/Solitary#107]
The wishes of the original developers are to use this project as a learning tool or for personal use.
We do **not** want the game to be **sold** in any state.

**Comment by lejara** [comment]
We need to get this stored before others contribute code/ assets

**Comment by PopeSpaceous** [comment]
So from my research, there are no licences that strictly prohibit the software from commercial use, that generally conflicts with the clause about no discrimination of people using the software. 
So the licence we should probably use is the GNU GPLv3 licence. 
This maintains the licence through all versions and iterations. If someone were to try to sell this, the GNU GPL licence would still be attached saying it is an open source software. 

Before applying the licence, I'm going to look into how it reacts with the sound and sample clips.

**Comment by Dragomegak** [comment]
https://www.quora.com/What-is-the-best-free-for-non-commercial-use-license-to-use-for-an-open-source-project
This seems to be an article that I think would be applicable to this case. 
Maybe have 2 licenses like the article says "So that some people (in your case, non-commercial use) get it under an open source license, and other people (commercial establishments) pay for it. ". 
Can't say I know of any licenses that would fit the project otherwise. Just my two cents.

**Comment by PopeSpaceous** [comment]
Yeah I remember reading that article, but thanks for linking it for others too @Dragomegak

**Comment by PopeSpaceous** [comment]
This issue has been resolved in PR #148
